name: pdfparsing
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'appnope=0.1.0=py27_0'
- !!python/unicode
  'backports=1.0=py27_0'
- !!python/unicode
  'decorator=4.0.11=py27_0'
- !!python/unicode
  'enum34=1.1.6=py27_0'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'get_terminal_size=1.0.0=py27_0'
- !!python/unicode
  'ipython=5.3.0=py27_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py27_0'
- !!python/unicode
  'jbig=2.1=0'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libtiff=4.0.6=3'
- !!python/unicode
  'olefile=0.44=py27_0'
- !!python/unicode
  'openssl=1.0.2l=0'
- !!python/unicode
  'path.py=10.3.1=py27_0'
- !!python/unicode
  'pathlib2=2.2.1=py27_0'
- !!python/unicode
  'pexpect=4.2.1=py27_0'
- !!python/unicode
  'pickleshare=0.7.4=py27_0'
- !!python/unicode
  'pillow=4.2.1=py27_0'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'prompt_toolkit=1.0.14=py27_0'
- !!python/unicode
  'ptyprocess=0.5.1=py27_0'
- !!python/unicode
  'pygments=2.2.0=py27_0'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'reportlab=3.4.0=py27_0'
- !!python/unicode
  'scandir=1.5=py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'simplegeneric=0.8.1=py27_1'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'traitlets=4.3.2=py27_0'
- !!python/unicode
  'wcwidth=0.1.7=py27_0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - awscli==1.11.98
  - backports.shutil-get-terminal-size==1.0.0
  - botocore==1.5.61
  - chardet==3.0.3
  - cycler==0.10.0
  - functools32==3.2.3.post2
  - futures==3.1.1
  - gdal==1.11.5
  - ipython-genutils==0.2.0
  - jmespath==0.9.3
  - matplotlib==2.0.2
  - nose==1.3.7
  - numpy==1.12.1
  - pdfminer.six==20151013
  - pdfplumber==0.5.5
  - pdfrw==0.3
  - prompt-toolkit==1.0.14
  - pyasn1==0.2.3
  - pycrypto==2.6.1
  - pypdf==1.13
  - pypdf2==1.26.0
  - pyspatialite==3.0.1
  - python-dateutil==2.6.0
  - pytz==2016.10
  - rsa==3.4.2
  - s3transfer==0.1.10
  - subprocess32==3.2.7
  - tqdm==4.14.0
  - unicodecsv==0.14.1
  - wand==0.4.4

